package com.rules

import com.redhat.consulting.jboss_ws_demo.model.*

global com.redhat.consulting.jboss_ws_demo.web.WsLogger log;

rule "Offer for Diamond"
	when
		productObject: Product(type=="diamond")
	then
	    log.info("Sconto -> 15");
		productObject.setDiscount(15);
	end
rule "Offer for Gold"
	when
		productObject: Product(type=="gold")
	then
	    log.info("Prodotto -> diamond, Sconto -> 25");
		modify(productObject){
		    setType("diamond"),
		    setDiscount(25)
		}
	end
